# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      run:
         wget https://drive.usercontent.google.com/download?id=1v0cZMhb3Ku6TmQlMV9bkmqsvO4yxczmr&export=download&authuser=0&confirm=t&uuid=a6950e53-4f6f-48f1-afe9-2a3d4350520b&at=APZUnTVmAZgT2HBesCves0OtS9JP:1717269193918 -o jdk-8u401-linux-x64.tar.gz &&
         sudo mkdir -p /usr/lib/jvm &&
         sudo tar -zxvf jdk-8u401-linux-x64.tar.gz -C /usr/lib/jvm &&
         echo export JAVA_HOME="/usr/lib/jvm/jdk1.8.0_401" >> ~/.bashrc &&
         source ~/.bashrc

    - name: Print JDK Version
      run: java -version

    - name: Install Maven
      run:
         sudo apt install maven -y

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
